config/routes.rb
Rankings::Application.routes.draw do
  root :to => 'application#index'

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  resource :sessions

  resources :players do
    get :ranking, on: :collection
    get :point_potential, on: :collection
    get :rating_history, on: :collection
  end

  resources :games do
    get :recalculate
  end
end

app/views/home/index.html.haml
.hero-unit
  %iframe{:height => 185, :width => 280, :frameborder => "0", :src => "http://www.youtube.com/embed/bqOZW6ckL0A", :class => "pull-right"}
    %h1 PingPongGuru
  %p Register an account for PingPongGuru and become the 'Guru'.
  %p
    = link_to 'Register for PingPongGuru', new_player_path(), :class => 'btn btn-large btn-primary'

app/views/home/rankings.haml
- content_for :title, 'Player Rankings'
.row
  .span6
    %table.table.table-striped
      - players = Player.order('score desc, name asc')
      %thead
        %tr
          %td #
          %td Name
          %td GP
          %td Score
          %td Streak
      %tbody
        - last_score = false
        - rank = 1
        - players.each do |player|
          %tr
            %td= rank if player.score != last_score
            - rank += 1 if player.score != last_score
            - last_score = player.score
            %td
              - if player.winning_streak > 2
                %span.label.label-important ON FIRE
              - if player.losing_streak > 1
                %span.label LOSING
              = player.name
            %td= player.games.count
            %td= player.score
            %td= player.streak