config/routes.rb
Rankings::Application.routes.draw do
  root :to => 'application#index'

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  resource :sessions

  resources :players do
    get :ranking, on: :collection
    get :point_potential, on: :collection
    get :rating_history, on: :collection
  end

  resources :games do
    get :recalculate
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  include LoadRankingAlgorithm

  has_and_belongs_to_many :teams
  has_many :games, through: :teams
  has_many :rating_histories, dependent: :destroy

  before_create :validate_player

  def validate_player
    Player.where(:name => name).exists? ? false : true
  end

  def games_won
    games.where(teams: { winners: true })
  end

  def games_lost
    games.where(teams: { winners: false })
  end

  def streak
    return games.count if games_lost.count == 0
    return -games.count if games_won.count == 0

    last_game_won = games_won.order('created_at desc').first.created_at
    last_game_lost = games_lost.order('created_at desc').first.created_at

    if last_game_won > last_game_lost
      return games_won.newer_than(last_game_lost).count
    else
      return -games_lost.newer_than(last_game_won).count
    end

  end

  def reset_rating
    self.rating = ranking_algorithm::DEFAULT_PLAYER_RATING
  end

  def rating
    read_attribute(:rating) || ranking_algorithm::DEFAULT_PLAYER_RATING
  end

  def default_profile_image_url
    nil
  end

  def profile_image_url(options={})
    google_image_url || default_profile_image_url
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    @player = Player.includes([:games, :teams, :rating_histories]).find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(player_params)
      redirect_to @player
    else
      render 'save_fail'
    end
  end

  def destroy
    Player.delete(params['id'])
    redirect_to new_player_path
  end

  def ranking
  end

  private

  def player_params
    params.require(:player).permit(:name, :rating)
  end
end

app/helpers/player_helper.rb
module PlayerHelper
  def create_ranker
    rank = 0
    last_rating = false
    skipped_ranks = 0
    lambda do |rating|
      if rating == last_rating
        skipped_ranks += 1
      else
        rank += skipped_ranks + 1
        skipped_ranks = 0
      end
      last_rating = rating
      rank
    end
  end

  def current_player
    return nil unless session[:player_id]
    @current_player ||= Player.where(id: session[:player_id]).first
  end
end

app/views/players/_form.haml
- @player ||= Player.new
= form_for @player, :html => {:class => 'default-form'} do |player|
  = player.hidden_field :id
  %h1 Enter your details here

  .input
    %label Name:
    = player.text_field :name, :placeholder => 'John Smith', :class => 'string'

  .buttons
    = player.submit :class => 'btn'

app/views/players/_player.haml
- cache player do
  .player{ :data => { 'player-id' => player.id } }
    %span.img{ :style => "background-image:url(#{player.profile_image_url(:bigger => true)})" }
    = link_to player.name, player, {:title => player.name}
  .history.spark_line
    %span.spark_line{ :id => "rating_spark_#{player.id}", :style => "width: #{[100,10 * player.games.count].min}%" }
    = spark_line "rating_spark_#{player.id}", player.rating_histories.includes(:game).limit(100).map(&:rating)
  .games-played
    %span= player.games.length
  .score
    %span= player.rating
  .streak.winning
    %span= player.streak

app/views/players/_possibility_matrix.haml
%table.matrix
  %colgroup
  -players.each do |player|
    %colgroup
  %thead
    %tr
      %th{ :colspan => players.count + 1 }
        Opponent
    %tr
      %th
        Player
      -players.each do |player|
        %th.player
          %span{:title => player.name}= player.name
  %tbody
    -players.each do |player|
      %tr
        %th.player
          %span{:title => player.name}= player.name
        -players.each do |opponent|
          -if player == opponent
            %td.empty/
          -else
            -possibilities = player.ranking_algorithm.possible_results(player.rating, opponent.rating)
            %td.score{:title => "#{number_to_human(possibilities[0][0])} / #{number_to_human(possibilities[0][1])}" }
              %strong
                = number_to_human(possibilities[0][0], :precision => 0)

app/views/players/_ranking.haml
- cache ['ranking table', players] do
  .header
    .player
      %span Player
    .history
      %span &nbsp;
    .games-played
      %span GP
    .score
      %span Score
    .streak
      %span Streak

  - ranker = create_ranker
  - players.each do |player|
    - rank = ranker.call(player.rating)
    .rank{:class => "rank-#{rank}", 'data-rank' => rank}
      = render player

app/views/players/_rating_history.haml
#rating_history_chart.span11{ :style => 'height: 600px;' }
  - if players.present? && Game.any?
    = line_graph 'rating_history_chart', players, { focus_radius: 10, group_by_dates: true }

app/views/players/_recent_games.haml
- games = Game.newest_first.limit(15).includes(teams: [:players]).to_a
- if games.any?
  .last-game= render(games.shift)
  .game-list= render(games)

app/views/players/edit.haml
- content_for :title, 'Edit player'
.row
  .span5
    = render 'form'

app/views/players/new.haml
- content_for :title, 'New player'
.content.medium
  = render 'form'

.content.medium
  %h1 Recently added players
  %ul
    - Player.order('created_at desc').limit(8).each do |player|
      %li
        = link_to player.name, player
        - if player.created_at > 1.minute.ago
          %span.label.label-success saved
        - elsif player.created_at > Time.new.yesterday
          %span.label new

app/views/players/point_potential.haml
- players = Player.order('rating desc, name asc').select { |player| should_show? player }
.content.nav-view
  = render 'shared/menu'

  #possibility-matrix.content.tab-view
    %h1 Point Potential Matrix
    = render 'possibility_matrix', players: players

#new-game.content.hide
  = render 'games/form'

- buffer_script "PingPong.initRankings();"

app/views/players/ranking.haml
- players = Player.order('rating desc, name asc').select { |player| should_show? player }
// Rankings
#rankings.content.nav-view
  = render 'shared/menu'

  // Ranking view
  #ranking-view.content.tab-view
    // Ranking list
    #ranking-list.content.medium
      %h1 Player Rankings
      = render 'ranking', players: players

    // Recent games
    #recent-games.content.medium
      = render 'recent_games'

// New game
#new-game.content.hide
  = render 'games/form'

- buffer_script "PingPong.initRankings();"

app/views/players/rating_history.haml
- players = Player.order('rating desc, name asc').select { |player| should_show? player }
.content.nav-view
  = render 'shared/menu'

  #history-graph.content.tab-view
    %h1 Rating History
    = render 'rating_history', players: players

#new-game.content.hide
  = render 'games/form'

- buffer_script "PingPong.initRankings();"

app/views/players/save.haml
- content_for :title, 'Player saved'

app/views/players/save_fail.haml
- content_for :title, 'Player not saved'

app/views/players/show.haml
- content_for :title, @player.name
%ul.tabs
  %li#tab-recent-games
    = link_to '#recent-games', {'data-content' => 'recent-games'} do
      Games Played
  %li#tab-history-graph
    = link_to '#history-graph', {'data-content' => 'history-graph'}  do
      History Graph
  %li#tab-player-edit
    = link_to('Edit '.html_safe << content_tag(:i, '', :class => 'icon-pencil'), edit_player_path(@player), {'data-content' => 'player-edit'} )

#recent-games.content.tab-view
  %h1 Games Played
  %table.table.table-striped
    %tbody
      - @player.games.order('created_at desc').where(:created_at => 30.days.ago..Time.now).each do |game|
        %tr
          - if game.winners.include? @player
            %td.span1
              %span.badge.badge-success.pull-right WON
            %td.span1
              = "#{game.winning_score}-#{game.losing_score}"
            %td
              - if game.winners.count > 1
                - teammate = (game.winners - [@player]).first
                = "with #{link_to teammate.name, teammate}".html_safe
              = "against"
              = "#{game.losers.map{|player| link_to(player.name, player)}.to_sentence}".html_safe
              = "on #{game.created_at.strftime('%d %b %y')}"
          - else
            %td.span1
              %span.badge.badge.pull-right LOST
            %td.span1
              = "#{game.losing_score}-#{game.winning_score}"
            %td
              - if game.losers.count > 1
                - teammate = (game.losers - [@player]).first
                = "with #{link_to teammate.name, teammate}".html_safe
              = "against"
              = "#{game.winners.map{|player| link_to(player.name, player)}.to_sentence}".html_safe
              = "on #{game.created_at.strftime('%d %b %y')}"

#history-graph.content.tab-view.hide
  %h1 Rating History
  #rating_chart.span9{ :style => 'height: 350px;' }
  = line_graph 'rating_chart', @player

#player-edit.content.tab-view.hide
  = render 'form'

-buffer_script "PingPong.initRankings();"
-buffer_script "$('#tab-recent-games a').click();"